### ------------------ 고객 -------------------
### 회원가입
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2022-12-22",
  "email": "jjae.3.lee@gmail.com",
  "name": "myName",
  "password": "pw",
  "phone": "string"
}

### 이메일 인증
GET http://localhost:8081/signup/customer/verify?email=jjae.3.lee@gmail.com&code=sQNs2jBGLZ

### 로그인
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "jjae.3.lee@gmail.com",
  "password": "pw"
}

### 회원 정보 조회
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQT3IxUmJrVFo3b2p3dy9xa3FMT2VmSXBya0xhY1p3ZXNpZURZT05ackxzPSIsImp0aSI6IkEzS3hjaEc5SFF1aWFrSDBxZVd2SUE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzY1ODE1MDUsImV4cCI6MTczNjY2NzkwNX0.iY69Gffj_IqXBdfViqyOTBkrMijS3OnflMXFjSkPlTI

### 잔액 변경
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQT3IxUmJrVFo3b2p3dy9xa3FMT2VmSXBya0xhY1p3ZXNpZURZT05ackxzPSIsImp0aSI6IkEzS3hjaEc5SFF1aWFrSDBxZVd2SUE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzY1ODE1MDUsImV4cCI6MTczNjY2NzkwNX0.iY69Gffj_IqXBdfViqyOTBkrMijS3OnflMXFjSkPlTI

{
  "from": "admin",
  "message": "돈 충전",
  "money": 150000
}

### ---------------- 셀러 ------------------
### 회원가입
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "2022-12-22",
  "email": "jjae.3.lee@gmail.com",
  "name": "seller",
  "password": "pw",
  "phone": "string"
}

### 이메일 인증
GET http://localhost:8081/signup/seller/verify?email=jjae.3.lee@gmail.com&code=OjtfDxNExp

### 로그인
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "jjae.3.lee@gmail.com",
  "password": "pw"
}

